const PERMISSIONS = {
  VIEW_USER: "VIEW_USER",
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  
  // POS
  VIEW_INVOICE: "VIEW_INVOICE",
  CREATE_INVOICE: "CREATE_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
  SELL_POS: "SELL_POS",

  // CUSTOMER
  VIEW_CUSTOMER: "VIEW_CUSTOMER",
  VIEW_STAFF: "VIEW_STAFF",
  CREATE_STAFF: "CREATE_STAFF",
  UPDATE_STAFF: "UPDATE_STAFF",
  DETAIL_STAFF: "DETAIL_STAFF",
};

module.exports = PERMISSIONS;
