const PERMISSIONS = {
  VIEW_USER: "VIEW_USER",
  CREATE_USER: "CREATE_USER",
  DELETE_USER: "DELETE_USER",
  VIEW_DASHBOARD: "VIEW_DASHBOARD",

  // POS
  VIEW_INVOICE: "VIEW_INVOICE",
  CREATE_INVOICE: "CREATE_INVOICE",
  DELETE_INVOICE: "DELETE_INVOICE",
  SELL_POS: "SELL_POS",

  // CUSTOMER
  VIEW_CUSTOMER: "VIEW_CUSTOMER",

  //STAFF
  VIEW_STAFF: "VIEW_STAFF",
  CREATE_STAFF: "CREATE_STAFF",
  UPDATE_STAFF: "UPDATE_STAFF",
  DETAIL_STAFF: "DETAIL_STAFF",

  // PRODUCT
  VIEW_PRODUCT: "VIEW_PRODUCT",
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  // PRODUCT UNIT
  VIEW_PRODUCT_UNIT: "VIEW_PRODUCT_UNIT",
  CREATE_PRODUCT_UNIT: "CREATE_PRODUCT_UNIT",
  UPDATE_PRODUCT_UNIT: "UPDATE_PRODUCT_UNIT",
  DELETE_PRODUCT_UNIT: "DELETE_PRODUCT_UNIT",

  // CATEGORY
  VIEW_CATEGORY: "VIEW_CATEGORY",
  CREATE_CATEGORY: "CREATE_CATEGORY",
  UPDATE_CATEGORY: "UPDATE_CATEGORY",
  DELETE_CATEGORY: "DELETE_CATEGORY",

  // STOCK
  UPDATE_STOCK: "UPDATE_STOCK",
  VIEW_PURCHASE_ORDER: "VIEW_PURCHASE_ORDER",
  UPDATE_PURCHASE_ORDER: "UPDATE_PURCHASE_ORDER",
  CREATE_PURCHASE_ORDER: "CREATE_PURCHASE_ORDER",
  RECEIVE_PURCHASE_ORDER: "RECEIVE_PURCHASE_ORDER",
  VIEW_PROBLEMATIC: "VIEW_PROBLEMATIC",
  PROCESS_PROBLEMATIC: "PROCESS_PROBLEMATIC",
  CREATE_PROBLEMATIC: "CREATE_PROBLEMATIC",

  //SHIFT
  VIEW_SHIFT: "VIEW_SHIFT",
  CREATE_SHIFT: "CREATE_SHIFT",
  UPDATE_SHIFT: "UPDATE_SHIFT",
  DELETE_SHIFT: "DELETE_SHIFT",
};

module.exports = PERMISSIONS;
